---
title: "Data Manipulation"
author: Madeline Sharp
output: github_document
---

This file is for doing data manipulation.

``` {r}
library(tidyverse)
```

Load the litters and pups datasets.

```{r}
litters_df =
  read_csv(
    "data/FAS_litters.csv",
    na = c("","NA", ".")
  )

litters_df = janitor::clean_names(litters_df)

pups_df =
  read_csv(
    "data/FAS_pups.csv",
    na = c("","NA", ".")
  )

pups_df = janitor::clean_names(pups_df)
```


## `select` some variables

```{r}
select(litters_df, group, litter_number)

select(litters_df, group:gd_of_birth)

select(litters_df, -group)

select(litters_df, starts_with("gd"))

select(litters_df, starts_with("gd"), group)

select(litters_df, GROUP = group, everything())

select(litters_df, LITTER = litter_number, everything())

select(litters_df, -starts_with("gd"))
```

a couple of alternatives

```{r}
# shorthand version of `select(litters_df, LITTER = litter_number, everything())`
rename(litters_df, GROUP = group)

# Jeff prefers subject ID is 1st variable. Put things to the front that are the highest levels of hierarchy in your data. `relocate()` puts object (cols) in a different order
relocate(litters_df, litter_number, gd0_weight)
```

In the pups data, select litter number, sex and PD ears.

```{r}
#select(pups_df, litter_number, sex, pd_ears)

select(pups_df, x1, x1_male_2_female, x3)
```

## 'filter` some rows

```{r}
filter(litters_df, gd_of_birth == 19)

filter(litters_df, pups_born_alive <= 5)

filter(litters_df, pups_born_alive != 6)

filter(litters_df, group %in% c("Con7", "Con8"))

filter(litters_df, group %in% c("Con7", "Con8"), pups_born_alive < 7)

filter(litters_df, pups_born_alive < 4 | pups_born_alive > 8)

drop_na(litters_df, gd0_weight)
```


In the pups dataset, keep only rows where PD walk is less than 11 and sex is 2

```{r}
filter(pups_df, x3 < 11, x1_male_2_female == 2)
```


## `mutate` to change some columns

